name: Home Management
version: "1.0"
slug: home_management
description: Configures desktop and Home Assistant interface on HDMI
arch:
  - arm64
startup: system
boot: auto
image: ghcr.io/ecokeley/home-management